---
title: "Project_2"
author: "Tianle Zhu"
date: "10/13/2020"
output: html_document
---

```{r warning=FALSE, message=FALSE, eval = F, echo=FALSE}
packages.used = as.list(
  c("dplyr", "tibble", "tidyverse", "shinythemes", "shiny", "sf", "RCurl",
    "stringr", "tmap", "tidyr", "ggplot2", "data.table", "ggmap", "DT",
    "choroplethr", "devtools", "DT", "readr", "lubridate", "leaflet", "tigris",
    "emojifont", "viridis", "plotly", "rgdal", "tmap", "RCurl", "tigris")
)
check.pkg = function(x){
  if(!require(x, character.only=T)) install.packages(x, character.only=T, dependence=T)
}

lapply(packages.used, require, character.only = TRUE)
```

## Dealing with covid_zip_code
```{r}
recent_modzcta <- read.csv("../data/coronavirus-data-master/recent/recent-4-week-by-modzcta.csv")
data_modzcta <- read.csv("../data/coronavirus-data-master/data-by-modzcta.csv")
case_by_boro <- read.csv("../data/coronavirus-data-master/by-boro.csv")
# drop redundant columns/rows
recent_modzcta_mod <- recent_modzcta[, -1:-2]
case_by_boro <- case_by_boro[1:5,]

# combine data frames
covid_modzcta <- cbind(data_modzcta, recent_modzcta_mod)

# get zip boundaries that start with 1
covid_zip_code <- zctas(cb = TRUE, starts_with = "1")
covid_zip_code <- covid_zip_code[as.numeric(covid_zip_code$ZCTA5CE10) < 11436, ]

covid_modzcta$MODIFIED_ZCTA <- as.character(covid_modzcta$MODIFIED_ZCTA)


# join zip boundaries and covid data 
covid_zip_code <- geo_join(covid_zip_code, 
                           covid_modzcta, 
                           by_sp = "GEOID10", 
                           by_df = "MODIFIED_ZCTA",
                           how = "left")

covid_zip_code <- na.omit(covid_zip_code)

covid_zip_code <- covid_zip_code[order(covid_zip_code$GEOID10), ]

# create two new variables 
covid_zip_code$TOTAL_POSITIVE_TESTS <- floor((covid_zip_code$PERCENT_POSITIVE/100)*covid_zip_code$TOTAL_COVID_TESTS)
covid_zip_code$TOTAL_POSITIVE_TESTS_4WEEK <- floor((covid_zip_code$PERCENT_POSITIVE_4WEEK/100)*covid_zip_code$NUM_PEOP_TEST_4WEEK)

# round off population to nearest whole number 
covid_zip_code$POP_DENOMINATOR <- floor(covid_zip_code$POP_DENOMINATOR)

# add latitude and longitude data to case_by_boro
latitude=c(40.8448,40.6782,40.7831,40.7282,40.5795)
longitude=c(-73.8648,-73.9442,-73.9712,-73.7949,-74.1502)
case_by_boro$Lat=latitude
case_by_boro$Long=longitude
case_by_boro <- case_by_boro %>%
  mutate(region=as.character(BOROUGH_GROUP))
save.image(file = '../app/output/covid_zip_code.RData')
```



```{r}
load("covid_zip_code.RData")
```

