---
title: "Project_2_Data_Collection"
author: "Tianle Zhu"
date: "10/5/2020"
output: html_document
---


# load libraries
```{r load libraries, message=FALSE, warning=FALSE, include=FALSE}
packages.used=as.list(
  c(
  "stringr",
  "dplyr",
  "tidyr",
  "ggplot2",
  "data.table",
  "ggmap",
  "choroplethr", 
  "devtools",
  "shiny",
  "DT",
  "readr", 
  "lubridate"
  )
)
check.pkg = function(x){
  if(!require(x, character.only=T)) install.packages(x, character.only=T, dependence=T)
}
if (!require("choroplethrZip")) 
  devtools::install_github('arilamstein/choroplethrZip@v1.5.0')
lapply(packages.used, check.pkg)
```

## get geocode by using google API You have to change to your own API KEY (Here I commend this chunk of code)
```{r include = FALSE, eval = FALSE, message = FALSE}
# testingcenter <- read.csv(file="../data/testingcenter.csv")
# testingcenter = testingcenter %>% separate(Names, c("Testing_Name", "Address"),sep = ":")
# # You have to change to your own API KEY
# register_google(key = "AIzaSyDGGPoCES2CaZN3xrgWu3peCGzbssefL23") 
# #geocoded <- data.frame(stringsAsFactors = FALSE)
# for(i in 1:nrow(testingcenter))
# {
#   # Print("Working...")
#   result <- geocode(testingcenter$Address[i], output = "latlona", source = "google")
#   testingcenter$lon[i] <- as.numeric(result[1])
#   testingcenter$lat[i] <- as.numeric(result[2])
#   testingcenter$geoAddress[i] <- as.character(result[3])
# }
# testingcenter$geoAddress <- as.character(testingcenter$geoAddress)
# testingcenter[testingcenter$geoAddress == "albany ave, brooklyn, ny, usa", ]$geoAddress <- "albany ave, brooklyn, ny, 11210, usa"
# testingcenter$zip = str_sub(testingcenter$geoAddres,-11, -6)
# write.csv(testingcenter, file="../output/testingcenter_geocode.csv", row.names = FALSE)
```

```{r message = FALSE}
Testcode <- read.csv(file="../app/output/testingcenter_geocode.csv")
Testplace_n = Testcode %>% group_by(zip) %>% summarise(value = n())
```

```{r load data}
nyccovid19 = read.csv('../data/coronavirus-data-master/data-by-modzcta.csv')
datatable(sample_n(nyccovid19,10))
```

```{r number of cases, message= FALSE}
nyccovid19=
  nyccovid19 %>%
  filter(MODIFIED_ZCTA > 0) %>%
  mutate(region=as.character(MODIFIED_ZCTA))

count.df=nyccovid19%>%
group_by(region)%>%
  summarise(
    value=COVID_CASE_COUNT
  )
header = TRUE
#save(count.df, file="../output/count.RData")
```

```{r death rate, message= FALSE}
nyccovid19=
  nyccovid19%>%
  filter(MODIFIED_ZCTA>0)%>%
  mutate(region=as.character(MODIFIED_ZCTA))

death_count.df=nyccovid19%>%
group_by(region)%>%
  summarise(
    value=COVID_DEATH_COUNT
  )
#save(death_count.df, file="../output/death_count.RData")
```

```{r nyc zipcode}
bronx_zip_code = c(10453, 10457, 10460,10458, 10467, 10468, 10451, 10452, 10456, 
                   10454, 10455, 10459, 10474, 10463, 10471, 10466, 10469, 10470, 
                   10475, 10461, 10462,10464, 10465, 10472, 10473)
brooklyn_zip_code = c(11212, 11213, 11216, 11233, 11238, 11209, 11214, 11228, 11204, 11218, 11219, 11230,
                      11234, 11236, 11239, 11223, 11224, 11229, 11235, 11201, 11205, 11215, 11217, 11231, 
                      11203, 11210, 11225, 11226, 11207, 11208, 11211, 11222, 11220, 11232, 11206, 11221, 
                      11237)
manhattan_zip_code = c(10026, 10027, 10030, 10037, 10039, 10001, 10011, 10018, 10019, 10036, 10029, 
                       10035, 10010, 10016, 10017, 10022, 10012, 10013, 10014, 10004, 10005, 10006, 
                       10007, 10038, 10280, 10002, 10003, 10009, 10021, 10028, 10044, 10065, 10075, 
                       10128, 10023, 10024, 10025, 10031, 10032, 10033, 10034, 10040)
queens_zip_code = c(11361, 11362, 11363, 11364, 11354, 11355, 11356, 11357, 11358, 11360, 11365, 11366, 
                     11367, 11412, 11423, 11432, 11433, 11434, 11435, 11436, 11101, 11102, 11103, 11104, 
                     11105, 11106, 11374, 11375, 11379, 11385, 11004, 11411, 11413, 11422, 11426, 11427, 
                     11428, 11429, 11414, 11415, 11416, 11417, 11418, 11419, 11420, 11421, 11368, 11369, 
                     11370, 11372, 11373, 11377, 11378, 11691, 11692, 11693, 11694, 11697)
staten_zip_code = c(10302, 10303, 10310, 10306, 10307, 10308, 10309, 10312, 10301, 10304, 10305, 10314)
nyc_fips = c(36005, 36047, 36061, 36081, 36085)

```

```{r nyc covid-19 confirmed cases}
zip_choropleth(count.df,
    title       = "NYC covid-19 confirmed cases",
    legend      = "Number of cases",
    zip_zoom = c(bronx_zip_code, brooklyn_zip_code, manhattan_zip_code, queens_zip_code, staten_zip_code))
```

```{r nyc covid-19 death count}
zip_choropleth(death_count.df,
    title       = "NYC covid-19 death cases",
    legend      = "Number of cases",
    zip_zoom = c(bronx_zip_code, brooklyn_zip_code, manhattan_zip_code, queens_zip_code, staten_zip_code)) 
```

```{r nyc testing center}
ggmap(get_map("Manhattan",source="google", 
              maptype = "roadmap",
              zoom=10, color = "bw")) + 
  geom_point(data = Testcode, aes(x=lon,y=lat), color='red') 
```

# Restaurant Information
```{r Message = F}
Restaurant = read.csv('../data/Open_Restaurant_Applications.csv')
Restaurant_sub <- Restaurant %>% dplyr::select(Restaurant.Name,BBL, Building.Number, Street, Borough, Postcode, Latitude, Longitude, Business.Address, Approved.for.Sidewalk.Seating, Approved.for.Roadway.Seating, Qualify.Alcohol, Time.of.Submission) %>% drop_na()

Restaurant_star = read.csv('../data/DOHMH_New_York_City_Restaurant_Inspection_Results.csv')
Restaurant_star_sub  <- Restaurant_star %>% dplyr::select(BBL, GRADE, GRADE.DATE, CUISINE.DESCRIPTION)

which(Restaurant_star_sub$BBL == 4014780001)
Restaurant_star_sub[which(Restaurant_star_sub$BBL == 4014780001),]
# Basic Business License (BBL)
combine_data <- left_join(Restaurant_sub, Restaurant_star_sub, by = "BBL")

# Dealing with GRADE variable in combine_data data

ind <- which(combine_data$GRADE == "")
combine_data <- combine_data[-ind,] %>% drop_na()
combine_data[combine_data$GRADE =="G",]$GRADE <- "C"
table(combine_data$GRADE)
combine_data$GRADE <- droplevels(combine_data$GRADE)



# Dealing with Grade Date

library(lubridate)
#combine_data$Time.of.Submission <- combine_data$Time.of.Submission %>% as.character()
combine_data$Time <- lapply(combine_data$Time.of.Submission, function(x){unlist(strsplit(as.character(x), " "))[1]}) %>% unlist() 
combine_data$GRADE.DATE <- combine_data$GRADE.DATE %>% as.character()
combine_data$GRADE.DATE <- ifelse(is.na(combine_data$GRADE.DATE), combine_data$Time, combine_data$GRADE.DATE)
combine_data$GRADE.DATE <- ifelse(combine_data$GRADE.DATE =="", combine_data$Time, combine_data$GRADE.DATE)
max(as.Date(combine_data$GRADE.DATE, format = "%m/%d/%Y"))

combine_data$GRADE.DATE <- combine_data$GRADE.DATE %>% as.Date(combine_data$GRADE.DATE, format = "%m/%d/%Y")

combine_data <- combine_data %>% distinct() %>% group_by(Restaurant.Name) %>% filter(GRADE.DATE == max(GRADE.DATE)) 

# Clean the CUISINE.DESCRIPTION 
Restaurant_cleaned <- combine_data 

CUISINE.DESCRIPTION_list <- unique(Restaurant_cleaned$CUISINE.DESCRIPTION) %>% as.character()
# index for regional DESCRIPTION_list

Rigional_list<- c("Spanish", "Indian", "Mediterranean", "American", "Mexican", "Italian", "Asian", 
              "Latin (Cuban, Dominican, Puerto Rican, South & Central American)", 
              "Greek", "Jewish/Kosher", "Indonesian", "Middle Eastern", "Chinese", "French", "Japanese", 
              "Thai", "Vietnamese/Cambodian/Malaysia", "Turkish", "Tapas", "Chinese/Cuban", "Korean", 
              "Caribbean", "Irish", "Continental", "Polish", "Peruvian", "Filipino", "English", 
              "Ethiopian", "African", "Californian", "German", "Russian", "Moroccan", "Brazilian",
              "Eastern European", "Australian",  "Chinese/Japanese", "Cajun", "Tex-Mex", "Hawaiian", 
              "Armenian", "Soul Food", "Portuguese", "Southwestern", "Scandinavian", "Egyptian", 
              "Bangladeshi", "Pakistani", "Afghan", "Iranian", "Creole/Cajun", "Creole")

index_rigional <- CUISINE.DESCRIPTION_list %in% Rigional_list 
CUISINE.DESCRIPTION_list[index_rigional]
# not regional DESCRIPTION_list
Not_Rigional_list <- CUISINE.DESCRIPTION_list[!index_rigional]
Not_Rigional_list 

African <- c("Ethiopian", "African", "Moroccan", "Egyptian")
Asian <- c("Indian", "Asian", "Indonesian", "Middle Eastern", "Chinese", "Japanese", 
             "Thai", "Vietnamese/Cambodian/Malaysia", "Turkish", "Chinese/Cuban", "Korean", 
             "Filipino", "Chinese/Japanese","Armenian", "Bangladeshi", "Pakistani", "Afghan", "Iranian")
European <-c("Spanish", "Mediterranean",  "Italian", "Greek", "Jewish/Kosher", "French", "Tapas", "Irish",
             "Polish", "English", "Ethiopian", "German", "Russian","Eastern European", "Portuguese",
             "Scandinavian","Creole/Cajun", "Creole")
Oceanian <-c("Turkish",  "Continental", "Australian", "Hawaiian")
Americas <- c("American", "Mexican", "Latin (Cuban, Dominican, Puerto Rican, South & Central American)",
              "Peruvian", "Brazilian", "Cajun", "Tex-Mex","Soul Food", "Southwestern", "Californian",
              "Caribbean")

Fast_food_list  <- c("Pizza/Italian", "Sandwiches", "Pizza", "Sandwiches/Salads/Mixed Buffet", 
                     "Soups & Sandwiches", "Hamburgers", "Hotdogs", "Hotdogs/Pretzels")
Dessert_list  <- c("Bagels/Pretzels", "Ice Cream, Gelato, Yogurt, Ices", "Juice, Smoothies, Fruit Salads",
                   "Café/Coffee/Tea", "Bakery", "Bottled beverages, including water, sodas, juices, etc.",
                   "Donuts", "Pancakes/Waffles", "Nuts/Confectionary")
Vegetarian_list  <- c("Vegetarian", "Salads")
Steak_list <- c("Steak")
BBQ_list <- c("Barbecue")
Others_list <- c("Other", "Not Listed/Not Applicable", "Delicatessen", "Chicken", "Soups")
Seafood_list <- c("Seafood")


Restaurant_cleaned$categories <- Restaurant_cleaned$CUISINE.DESCRIPTION %>% as.character()
is(Restaurant_cleaned$categories)
Restaurant_cleaned[Restaurant_cleaned$categories %in% African,]$categories <- "African"
Restaurant_cleaned[Restaurant_cleaned$categories %in% Asian,]$categories <- "Asian"
Restaurant_cleaned[Restaurant_cleaned$categories %in% European,]$categories <- "European"
Restaurant_cleaned[Restaurant_cleaned$categories %in% Oceanian,]$categories <- "Oceanian"
Restaurant_cleaned[Restaurant_cleaned$categories %in% Americas,]$categories <- "Americas"
Restaurant_cleaned[Restaurant_cleaned$categories %in% Fast_food_list,]$categories <- "Fast_food"
Restaurant_cleaned[Restaurant_cleaned$categories %in% Dessert_list,]$categories <- "Dessert"
Restaurant_cleaned[Restaurant_cleaned$categories %in% Vegetarian_list,]$categories <- "Vegetarian"
Restaurant_cleaned[Restaurant_cleaned$categories %in% Steak_list,]$categories <- "Steak"
Restaurant_cleaned[Restaurant_cleaned$categories %in% BBQ_list,]$categories <- "BBQ"
Restaurant_cleaned[Restaurant_cleaned$categories %in% Others_list,]$categories <- "Others"
Restaurant_cleaned[Restaurant_cleaned$categories %in% Seafood_list,]$categories <- "Seafood"
unique(Restaurant_cleaned$categories)

#c("European", "Asian", "Fast_food", "Seafood", "Vegetarian", "Americas", "Dessert", "Others", "BBQ", "Oceanian", "Steak", "African")

Restaurant_cleaned_Or <- Restaurant_cleaned

write.csv(Restaurant_cleaned_Or, file="../data/Restaurant_cleaned_Or.csv", row.names = FALSE)


Restaurant_cleaned <- Restaurant_cleaned_Or %>% select("Restaurant.Name", "Business.Address","GRADE", "Postcode", "Latitude", "Longitude", "CUISINE.DESCRIPTION", "categories")

write.csv(Restaurant_cleaned, file="../data/Restaurant_cleaned.csv", row.names = FALSE)

read_csv("../data/Restaurant_cleaned.csv")
```

```{r nyc restaurant GRADE, warning = FALSE}
# # register_google(key = "") 
# 
# p1 <- ggmap(get_map("Manhattan",source="google", maptype = "roadmap", zoom=12, color = "bw"))
# p1 + geom_point(data = Restaurant_cleaned , aes(x = Longitude, y = Latitude, color = GRADE, shape = GRADE), alpha = 0.2, size = 2) 
```

```{r nyc restaurant GRADE by Borough, warning = FALSE}
# p1 + facet_wrap(~Borough, ncol = 2) + geom_point(data = Restaurant_cleaned, aes(x = Longitude, y = Latitude, color = GRADE, shape = GRADE), alpha = 0.2, size = 2) 
```

```{r nyc restaurant GRADE by Borough, warning = FALSE}
# p1 + facet_wrap(~ Qualify.Alcohol, ncol = 2) + geom_point(data = Restaurant_cleaned, aes(x = Longitude, y = Latitude, color = GRADE, shape = GRADE), alpha = 0.2, size = 2) 
```

# center_zipcode
```{r warning = False}
us_zip_code <- read_delim("../data/us-zip-code-latitude-and-longitude.csv",  ";")
us_zip_code 

zip_zoom = c(bronx_zip_code, brooklyn_zip_code, manhattan_zip_code, queens_zip_code, staten_zip_code)
zip_zoom
length(zip_zoom)
us_zip_code$Zip <- as.numeric(us_zip_code$Zip)
# zip code

ind_which = zip_zoom %in% as.numeric(us_zip_code$Zip)
zip_zoom[ind_which]
zip_zoom[!ind_which]

temp_zipcode = us_zip_code %>% filter(us_zip_code$Zip %in% zip_zoom[ind_which]) %>% select(Zip, City, Latitude, Longitude)
temp_zipcode
is(temp_zipcode$City)

add_zip <- as.data.frame(matrix(c(c(10004, 10065, 10075), c("New York", "New York", "New York"), c(40.7039,40.7645,40.772 ), c(-74.0139, -73.9624, -73.9558)), nrow = 3, ncol = 4, byrow = F))
colnames(add_zip) <- c("Zip", "City", "Latitude", "Longitude")
add_zip[c(1, 3, 4)] <- sapply(add_zip[c(1, 3, 4)], as.numeric)
add_zip$City <- as.character(add_zip$City)

center_zipcode <- rbind(temp_zipcode, add_zip)
write.csv(center_zipcode, file="../app/output/center_zipcode.csv", row.names = FALSE)


```

## Dealing with covid_zip_code
```{r}
recent_modzcta <- read.csv("../data/coronavirus-data-master/recent/recent-4-week-by-modzcta.csv")

# drop redundant columns/rows
recent_modzcta_mod <- recent_modzcta[, -1:-2]
case_by_boro <- case_by_boro[1:5,]

# combine data frames
covid_modzcta <- cbind(data_modzcta, recent_modzcta_mod)

# get zip boundaries that start with 1
covid_zip_code <- zctas(cb = TRUE, starts_with = "1")
covid_zip_code <- covid_zip_code[as.numeric(covid_zip_code$ZCTA5CE10) < 11436, ]

covid_modzcta$MODIFIED_ZCTA <- as.character(covid_modzcta$MODIFIED_ZCTA)


# join zip boundaries and covid data 
covid_zip_code <- geo_join(covid_zip_code, 
                           covid_modzcta, 
                           by_sp = "GEOID10", 
                           by_df = "MODIFIED_ZCTA",
                           how = "left")

covid_zip_code <- na.omit(covid_zip_code)

covid_zip_code <- covid_zip_code[order(covid_zip_code$GEOID10), ]

# create two new variables 
covid_zip_code$TOTAL_POSITIVE_TESTS <- floor((covid_zip_code$PERCENT_POSITIVE/100)*covid_zip_code$TOTAL_COVID_TESTS)
covid_zip_code$TOTAL_POSITIVE_TESTS_4WEEK <- floor((covid_zip_code$PERCENT_POSITIVE_4WEEK/100)*covid_zip_code$NUM_PEOP_TEST_4WEEK)

# round off population to nearest whole number 
covid_zip_code$POP_DENOMINATOR <- floor(covid_zip_code$POP_DENOMINATOR)

# add latitude and longitude data to case_by_boro
latitude=c(40.8448,40.6782,40.7831,40.7282,40.5795)
longitude=c(-73.8648,-73.9442,-73.9712,-73.7949,-74.1502)
case_by_boro$Lat=latitude
case_by_boro$Long=longitude
case_by_boro <- 
  case_by_boro%>%
  mutate(region=as.character(BOROUGH_GROUP))
save.image(file = '../app/output/covid_zip_code.RData')
```

